#include "math.h" // Auto-generated by rpcgen
#include <stdio.h>

// Notice the _1_svc suffix and the use of pointers!
int * add_1_svc(numbers *argp, struct svc_req *rqstp) {
    
    // Result MUST be static because we are returning a pointer to it over the network
    static int result; 
    
    printf("Server received request: %d + %d\n", argp->a, argp->b);
    
    // Do the actual math
    result = argp->a + argp->b;
    
    printf("Server sending back: %d\n", result);
    
    return &result;
}