#include "math.h" // Auto-generated by rpcgen
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
    CLIENT *clnt;
    int *result;
    numbers args;

    // We need 4 arguments: ./client <IP> <Num1> <Num2>
    if (argc != 4) {
        printf("Usage: %s <server_ip> <num1> <num2>\n", argv[0]);
        exit(1);
    }

    // 1. Create the client connection (using UDP here)
    clnt = clnt_create(argv[1], MATH_PROG, MATH_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(argv[1]);
        exit(1);
    }

    // 2. Load the numbers into our struct
    args.a = atoi(argv[2]);
    args.b = atoi(argv[3]);

    // 3. Call the remote procedure just like a normal function!
    result = add_1(&args, clnt);
    
    if (result == NULL) {
        clnt_perror(clnt, "RPC Call Failed");
    } else {
        printf("Result from Server: %d\n", *result);
    }

    // 4. Clean up
    clnt_destroy(clnt);
    return 0;
}